# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.0.0-beta2
group=com.starskyxiii.collapsible_groups
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Collapsible Groups
mod_author=StarskyXIII
mod_id=collapsible_groups
license=MIT
credits=
description=Collapsible item/fluid/ingredient groups for JEI/EMI.
minecraft_version_range=[1.20.1, 1.20.2)

# Fabric
fabric_version=0.92.12+1.20.1
fabric_loader_version=0.16.14

# Forge
forge_version=47.4.10
forge_loader_version_range=[47,)
jei_version=15.20.0.102
emi_version=1.1.24+1.20.1
kubejs_version=2001.6.5-build.26
rhino_version=2001.2.3-build.10
architectury_version=9.2.14
modmenu_version=7.2.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
